### ISSUE TITLE
Marketplace proposal

### ISSUE THREAD

**Issue by lukehedger** [meta-network/meta-identity-claims-service#16]
- [ ] Outline a proposal for a META Identity Claims Service marketplace

---

**Problem**
Currently, the META Identity Claims Services that are available to participants in the META Network are maintained at application level ie. the place where they are consumed. For example, the META ID dapp provides an interface to all of the current claims services by maintaining a list of services, some data about each service and the URL to send a verification request to. If another dapp wants to offer a similar interface, it too will have to maintain a similar list. Additionally, whenever new claims services are created they must ask the developers of those dapps to add their service.

**Solution**
The problems of registering new claims services and maintaining an accurate record of the available services can be solved by introducing a 'marketplace' for claims services to the META network. This marketplace would have an API that allows clients to write and read to the underlying dataset. The API would need to have access control rules, particularly around writes. It could be accessed via an ENS record that points to the latest hash available eg. `marketplace.id.meta`.

**Comment by MrTibbles** [comment]
🐕 
Very keen to discuss this further, as we should use a similar/same approach for [Smart Content](https://github.com/jaakmusic/smart-content-contracts) licenses.

**Comment by vaughnmck** [comment]
Interesting - what if the marketplace was a free market for ID verification services?
i.e. 
0.1 META monthly to connect your Spotify
0.05 for DDEX
0.001 META to Stakers 
...

Might provide an incentive for companies to build these claims services.

**Comment by lukehedger** [comment]
@MrTibbles 100%, could be pretty much the same model. So, we should design this 'marketplace' concept in a generic way.

@vaughnmck Definitely should build economics into it. Also, when a claim is used to make a judgement (ie. is this identity authorised to access this data) the consumer of that claim pays a fee, which is then shared between the claim issuer and any Stakers of that claim/identity. The fact that the claim has been trusted is also an endorsement of that claim and should be reflected in the network - I saw this [referenced in Deloitte's SmartID](https://github.com/SmartIdentity/smartId-contracts#value-of-the-identity--attribute--endorsement-model).

**Comment by lukehedger** [comment]
Closing in favour of https://github.com/meta-network/docs/pull/16. Discussion and review of proposal should continue there.
